name: Ubuntu 24.04 Rolling Build

on:
  pull_request:
  push:
    branches:
      - iron

jobs:
  Build:
    runs-on: self-hosted
    container:
      image: osrf/ros:rolling-desktop-full

    steps:
    - name: Update
      run: apt-get update

    - name: Install PIP
      run: apt-get install -y python3-pip lcov python3-colcon-lcov-result python3-colcon-coveragepy-result

    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Run Tests
      uses: ros-tooling/action-ros-ci@0.3.13
      with:
        target-ros2-distro: rolling
        import-token: ${{ secrets.GITHUB_TOKEN }}
        vcs-repo-file-url: "${{ github.workspace }}/iron.repos"

    - name: Upload Logs
      uses: actions/upload-artifact@v1
      with:
        name: colcon-logs
        path: ros_ws/log
      if: failure()
